### ISSUE TITLE
Instructions on devops seem to be insufficient

### ISSUE THREAD

**Issue by papotte** [ahrnee/nestjs-bff#2]
Hello, I am trying to start with your project, but I keep getting dependency erros on npm install. 
I am not sure why, but npm doesn't seem to be able to locate your packages @nestjs-bff/global and @nestjs-bff/backend while running `npm run install-all-with-docker`

The error looks something like this:
![image](https://user-images.githubusercontent.com/21336477/51749362-707b3880-20af-11e9-8719-f1e473cf8900.png)

Is it possible there's additional packages which need to be preinstalled?

Thanks for your help

**Comment by ahrnee** [comment]
@papotte - this is fixed now.  Get the latest version, and follow the instructions on the [DevOps documentation page](https://github.com/ahrnee/nestjs-bff/blob/master/devops/README.md)

Note - there has been a file structure change as part of this fix
