### ISSUE TITLE
Database migrations

### ISSUE THREAD

**Issue by simonschmoll** [ahrnee/nestjs-bff#21]
Hi, thanks for putting together this repo!

I have a question regarding the migration of your database.
Which tool did you use? The setup looks like migrate-mongoose, but you are using a typescript file for your database migrations. Could you elaborate on the migration setup? I tried the migrate-mongoose library, but it does not support typescript.

**Comment by ahrnee** [comment]
Hi @simonschmoll  - I also had trouble finding a Mongo migration library, so ended up using [Migrate Mongoose](https://github.com/balmasi/migrate-mongoose), and modifiying it to suit my needs.

The related code is here: https://github.com/ahrnee/nestjs-bff/tree/master/pkg-bff/backend/src/shared/migrations

The attribution page is here: https://github.com/ahrnee/nestjs-bff/blob/master/docs/ATTRIBUTIONS.md
