### ISSUE TITLE
B: two broken links in README.md

### ISSUE THREAD

**Issue by mathieucaroff** [ahrnee/nestjs-bff#4]
The last occurrence of `DEVOPS` points to the wrong path. A bit above that link, the link to the attribution page is broken too.

* Devops
  * (404: https://github.com/ahrnee/nestjs-bff/blob/master/devops/README.md)
  * (200: https://github.com/ahrnee/nestjs-bff/blob/master/DEVOPS.md)
* Attribution
  * (404: https://github.com/ahrnee/nestjs-bff/blob/master/attributions/ATTRIBUTIONS.md)
  * I searched for "ATTRIBUTIONS" and found:
     (200: https://github.com/ahrnee/nestjs-bff/blob/master/docs/ATTRIBUTIONS.md)

**Comment by ahrnee** [comment]
@mathieucaroff - good catch, thanks for submitting the issue. I'll take care of this shortly

**Comment by ahrnee** [comment]
These links have been fixed in the README file

**Comment by dimonuch** [comment]
Hello
Now in "ahrnee/nestjs-bff/blob/master/README.md" in the section "Readme Navigation" Devops link points to itself (the same file) and not to "ahrnee/nestjs-bff/blob/master/DEVOPS.md"

May be this is not right?

**Comment by ahrnee** [comment]
Good catch @dimonuch. This is now fixed
