### ISSUE TITLE
Unable to start project

### ISSUE THREAD

**Issue by lucasdiedrich** [ahrnee/nestjs-bff#5]
Using the readme from the project, i can`t start it:

1. yarn run install-all doesn`t exist.
![image](https://user-images.githubusercontent.com/817482/61183495-5c54d480-a618-11e9-9323-88bfe13adb6b.png)
But yarn install seems to resolve the problem

2. yarn install && yarn start doesn`t work. The starting proccess prompts me missing internal deps from the project, similar from #2 . I should use yarn install && yarn build && yarn start to work.

I tried using the master branch. 

Thanks.

**Comment by aoighost** [comment]
I'm having similar issues.

**Comment by ahrnee** [comment]
There was some out-of-date installation and execution instructions in the Frontend and Backend README files. These have now been removed, and reference the DevOps README which contains the [up-to-date instructions](https://github.com/ahrnee/nestjs-bff/blob/master/DEVOPS.md).

Apologies for the slow response. Hopefully this takes care of the problem.
